### ISSUE TITLE
Always asks for password

### ISSUE THREAD

**Issue by calvingit** [yangfeicheung/Shadowsocks-X#1]
Mac: 10.13.1
Open the preferences, do nothing, then present a dialog asking for password. Even quit the application, it's asking for password as well.

**Comment by yangfeicheung** [comment]
@calvingit  
basically,there are two things that needs password because it needs the permission,the first one is the network setting tool contained in the app,so u don't have to manually setup the socks proxy,
the second one is the kcptun tool if you set up to use ss over kcptun. I guess u might reject the request,right? If not so, please tell me more details

**Comment by yangfeicheung** [comment]
solved,download again

**Comment by yangfeicheung** [comment]
check the solution here:

https://github.com/yangfeicheung/Shadowsocks-X/issues/16
