### ISSUE TITLE
MacPro 休眠重新唤醒后客户端退出

### ISSUE THREAD

**Issue by tony-haibo-zhu** [yangfeicheung/Shadowsocks-X#23]
mac pro 上有一定几率休眠重新唤醒后，客户端消失。并且无法正常上网，重新打开客户端后正常。OSX10.13.2

**Comment by yangfeicheung** [comment]
@tony-haibo-zhu  ok,thanks for telling this, I would fix this issue asap

**Comment by tony-haibo-zhu** [comment]
@yangfeicheung l can't promise you this problem occurs every time. The only one thing l can provide is sleep laptop and reopen laptop and no more details. So sorry about that but maybe l can send the app logs to you. Can you tell me the location of app logs on Mac Pro ?

**Comment by yangfeicheung** [comment]
@tony-haibo-zhu  thanks for that, but I think I've already found the solution, the problem is that I can reproduce the issue on my pc, every time it sleeps and wake, nothing happens, the app works as before, so maybe if it happens a lot on ur end, can you test it for me? e.g. I fix this and then send u a copy.

**Comment by yangfeicheung** [comment]
@tony-haibo-zhu  I've tried to fix this issue, can u try this one and see if it works?

[ssx-bugfix.zip](https://github.com/yangfeicheung/Shadowsocks-X/files/1688415/ssx-bugfix.zip)

**Comment by tony-haibo-zhu** [comment]
@yangfeicheung l have used it two days and that issue doesn't appear again. l think it's time to add  this fix to next release and this issue can be closed. 
Thanks agin.

**Comment by yangfeicheung** [comment]
@tony-haibo-zhu  ok, thanks for ur test, I would add this fix to next release, thanks again. Do let me know if there's any issue
