### ISSUE TITLE
MAC版没问题 但是WINDOWS版为什么开启海外模式只能连国内网站国外网站上不去了

### ISSUE THREAD

**Issue by IXueGaoI** [yangfeicheung/Shadowsocks-X#35]
是否需要额外设置?

**Comment by yangfeicheung** [comment]
1. open app
2. login
3. choose Enable System Proxy
4. choose a server
then you should be good to go, if you have any issue, do let me know

**Comment by IXueGaoI** [comment]
@yangfeicheung 

I guess my question should be how could I create "Oversea Mode" in Windows version. As there's no pre-made mode in windows, how to create a rule that only chinese ip is access via ss server while the rest not? 
Thank you~

**Comment by yangfeicheung** [comment]
@IXue, hi, sorry to tell you that on Windows, right now no Oversea Mode is available, we might add it later, Currently you can use Global Mode partially as Oversea Mode, choose a cn server, but under Global Mode with a cn server, you can visit prohibited sites, since your request is sent out by a cn server, hope you can understand that. We will add Oversea Mode later.
