### ISSUE TITLE
after i turn it off network doesnt work?

### ISSUE THREAD

**Issue by nadia-am** [yangfeicheung/Shadowsocks-X#41]
after i turn off shadowsocks network doesnt work. in my setting it is connected but it doesnt work.why?

**Comment by kainobody** [comment]
nadia,

had same problem - my problem was i used the itunes app version. if that sounds like you, try downloading the socksx app through another channel. you should have access to the user guides which will link to what you need to install

**Comment by kainobody** [comment]
https://www.sednax.com/help.php can find here

**Comment by nadia-am** [comment]
i went to my network setting and deactive using socket proxy.
tnx anyway

**Comment by yangfeicheung** [comment]
@nadia-am
There are actually two versions of this app, one is App-Store version, which you download from app store, another is Non-App-Store version, which you download from our website here:
https://www.sednax.com/download.php

if you want to use App-Store version, you need to remember that, you always needs to turn on Socks Proxy setting when you open ShadowsocksX, and remove the Socks Proxy setting when you exit ShadowsocksX, you have to do this manually, you can  check how to do it here:
https://www.sednax.com/help-network.php

However, if you use Non-App-Store version, all this can be done automatically, that's why we create this version, because Apple doesn't allow apps to config network if you want to publish it to app store, it's strictly restricted.

**Comment by pucca601** [comment]
hi @yangfeicheung  i am using the Non-App-Store version and it always asked me to allow the network config to be altered after I changed the current system username. How to solve it? where can I recover it?

**Comment by yangfeicheung** [comment]
@pucca601
check this page:
https://github.com/yangfeicheung/Shadowsocks-X/issues/16

**Comment by flower-iroseka** [comment]
I want to use the Non-AppStore app to listen on, for example port 1080 to connect certain programs, but ignore others. With old versions I can do this by simply turning it off, but this version won't listen on port 1080 when I turn SSX off. Is there any workarounds?
